.\" Manpage for nuseradd.
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 1 "14 Apr 2012" "2012-04-14" "JFBPDF Man Page"
.SH NAME
JFBPDF \- framebuffer PDF viewer for Linux
.SH SYNOPSIS
jfbpdf [-r rotation] [-z zoom x10] [-p page] path_to_pdf.pdf
.SH DESCRIPTION
JFBPDF is a simple PDF viewer for the Linux framebuffer. It is originally based
on the fbpdf program by Ali Gholami Rudi and uses the MuPDF library for parsing
and rendering PDF files.
.SH OPTIONS
.TP
\fB\-z n\fR
specify initial zoom to be n x 10 percent (between 1 and 30)
.TP
\fB\-r n\fR
specify initial rotation to be n degrees counter-clockwise
.TP
\fB\-p n\fR
go to page n on start up
.SH KEY BINDINGS - MAIN VIEW
JFBPDF has a set of vi-like key bindings and many commands can be prefixed with a number. These are shown with a [n] prefix below.
.TP
[n]\fBarrow keys\fR, [n]\fBh\fR/\fBl\fR/\fBk\fR/\fBj\fR
Move left/right/up/down.
.TP
[n]\fBSpace\fR/\fB^D\fR/\fBPageDown\fR
Move n screens down. Default is 1.
.TP
[n]\fBu\fR/\fBBackSpace\fR/\fBPageUp\fR
Move n screens up. Default is 1.
.TP
[n]\fB=\fR/\fB+\fR
Zoom in n times. Default is 1.
.TP
[n]\fB\-\fR
Zoom out n times. Default is 1.
.TP
\fBs\fR
Zoom to screen width.
.TP
\fBTab\fR
Open outline view (table of contents).
.TP
\fBq\fR
Quit.
.TP
[n]\fBG\fR
Go to page n. Default is last page.
.TP
\fBm\fRx
Save current position in document in bookmark `x'. `x' can be any letter.
.TP
\fB`\fRx, \fB'\fRx
Jump to saved position `x'.
.TP
[n]\fBr\fR
Set rotation to n degrees. Default is 0.
.TP
\fBHome\fR/\fBEnd\fR
Go to first / last page.
.TP
[n]\fBz\fR
Set zoom to n x 10 percent.
.TP
\fBi\fR
Print information on the current document.
.TP
\fBEsc\fR
Clear numeric prefix.
.TP
\fBH\fR/\fBM\fR/\fBL\fR
Show top\fR/\fBmiddle\fR/\fBbottom of current page.
.TP
\fB^L\fR
Redraw screen.
.TP
\fBe\fR
Reload current file.
.TP
[n]\fBJ\fR/\fBK\fR, [n]\fB^F\fR/\fB^B\fR,
Go down / up n pages. Default is 1.
.SH KEY BINDINGS - OUTLINE VIEW
The outline view is toggled by the \fBTab\fR key.
.TP
\fBTab\fR/\fBq\fR/\fBEsc\fR
Toggle outline view.
.TP
\fBj\fR/\fBDown\fR, \fBk\fR/\fBUp\fR
Move up or down.
.TP
\fBEnter\fR/\fBg\fR
Go to selected item.
.TP
\fBSpace\fR
Fold/unfold selected item.
.TP
\fB=\fR/\fB+\fR/\fBRightArrow\fR
Unfold current item.
.TP
\fB-\fR/\fBLeftArrow\fR
Fold current item.
.TP
\fBzR\fR
Unfold all.
.TP
\fBzM\fR
Fold all.
.SH BUGS
This software is still experimental and thus likely contains lots of bugs. You are welcome to submit any bugs or improvement suggestions to the author.
.SH AUTHOR
Chuan Ji (jichuan89 AT gmail.com)
