.\" Manpage for JFBView.
.\" Contact ji@chu4n.com to correct errors or typos.
.TH man 1 "23 Sep 2014" "2014-09-23" "JFBView Man Page"
.SH NAME
JFBView \- PDF and image viewer for the Linux framebuffer.
.SH SYNOPSIS
jfbview [OPTIONS] FILE
.SH DESCRIPTION
JFBView is a PDF and image viewer for the Linux framebuffer. It is very fast and
has a number of advanced and unique features.
.SH OPTIONS
.TP
\fB--help\fR, \fB-h\fR
Shows help message.
.TP
\fB--fb=\fR/path/to/dev
Specifies the path to the output framebuffer device. The default is /dev/fb0.
.TP
\fB--page=\fRn, \fB\-p\fR n
Go to page n on start up.
.TP
\fB--zoom=\fRn, \fB\-z\fR n
Set initial zoom to be n percent. For example, "-z 75" sets zoom to 75%.
.TP
\fB--zoom_to_fit\fR
Start in zoom-to-fit mode.
.TP
\fB--zoom_to_width\fR
Start in zoom-to-width mode. This is the default.
.TP
\fB--rotation=\fRn, \fB-r\fR n
Set initial rotation to n degrees clockwise.
.TP
\fB--format=image\fR
Forces the program to treat the input file as an image.
.TP
\fB--format=pdf\fR
Forces the program to treat the input file as a PDF. By default, the file format
is detected based on its extension. If the file does not have a ".pdf" (case is
ignored) extension, this will force JFBView to load it as a PDF.
.TP
\fB--cache_size=\fRn
Selects the number of pages to cache. JFBView has a in-memory cache of pages
rendered at a particular zoom and rotation setting. However, you may wish to
adjust the cache size down if this cache is consuming too much memory, or you
may wish to adjust the cache size up for increased performance. If you have an
older machine with limited RAM you may want to set it close to zero.
.SH KEY BINDINGS - MAIN VIEW
JFBView has a set of vi-like key bindings and many commands can be prefixed with
a number. These are shown with a [n] prefix below.
.TP
\fBq\fR
Quit.
.TP
\fBTab\fR
Open \fBOUTLINE VIEW\fR (table of contents, i.e., TOC; see below).
.TP
\fB/\fR
Open \fBSEARCH VIEW\fR (see below).
.TP
[n]\fBarrow keys\fR, [n]\fBh\fR/\fBl\fR/\fBk\fR/\fBj\fR
Move left/right/up/down.
.TP
[n]\fBSpace\fR/\fB^F\fR
Move n screens down. Default is 1.
.TP
[n]\fB^B\fR
Move n screens up. Default is 1.
.TP
[n]\fBPageDown\fR/\fBPageUp\fR
Go down / up n pages. Default is 1.
.TP
[n]\fB=\fR/\fB+\fR
Zoom in n times. Default is 1.
.TP
[n]\fB\-\fR
Zoom out n times. Default is 1.
.TP
\fBs\fR
Zoom to screen width.
.TP
\fBa\fR
Zoom to fit.
.TP
\fBHOME\fR/\fBEND\fR
Go to first / last page in document.
.TP
[n]\fBG\fR/\fBg\fR
Go to page n. Default for \fBG\fR is last page; default for \fBg\fR is first
page.
.TP
[n]\fBm\fR
Save current position, zoom and rotation in document in bookmark n. The default
is 0.
.TP
[n]\fB`\fR
Restore saved position, zoom and rotation in bookmark n. The default is 0.
.TP
[n]\fBr\fR
Set rotation to n degrees. Default is 0.
.TP
[n]\fB>\fR/\fB.\fR
Rotate 90 degrees clockwise n times. Default is 1.
.TP
[n]\fB<\fR/\fB,\fR
Rotate 90 degrees counter-clockwise n times. Default is 1.
.TP
[n]\fBz\fR
Set zoom to n percent.
.TP
\fBe\fR
Reload current file from disk.
.SH KEY BINDINGS - OUTLINE VIEW
The outline view is toggled by the \fBTab\fR key.
.TP
\fBTab\fR/\fBq\fR/\fBEsc\fR
Toggle outline view.
.TP
\fBj\fR/\fBDown\fR, \fBk\fR/\fBUp\fR
Move down or up.
.TP
\fBPageDown\fR/\fBPageUp\fR
Go down / up one page.
.TP
\fBEnter\fR/\fBg\fR
Go to selected item.
.TP
\fBSpace\fR
Fold/unfold selected item.
.TP
\fBzR\fR
Unfold all.
.TP
\fBzM\fR
Fold all.
.SH KEY BINDINGS - SEARCH VIEW - SEARCH TEXT
.TP
\fBEsc\fR
Toggle search view.
.TP
\fBEnter\fR
Start search.
.TP
\fBTab\fR/\fBDown\fR/\fBPageDown\fR
Go to search results.
.SH KEY BINDINGS - SEARCH VIEW - SEARCH RESULTS
.TP
\fBq\fR/\fBEsc\fR
Toggle search view.
.TP
\fBSpace\fR/\fBEnter\fR/\fBg\fR
Go to selected item.
.TP
\fBj\fR/\fBDown\fR, \fBk\fR/\fBUp\fR
Move down or up.
.TP
\fBPageDown\fR/\fBPageUp\fR
Go down / up one page.
.TP
\fBTab\fR/\fB/\fR
Go to search text.
.SH BUGS
This software is still experimental and thus likely contains lots of bugs. You
are welcome to submit any bugs or improvement suggestions to the author.
.SH AUTHOR
Chuan Ji (ji@chu4n.com)
